//! Oracle regeneration test script.
//!
//! Overwrites `res/expected/oracle_*.json` with the current `resolve_lean` output.
//! Run when the algorithm changes intentionally, then review the git diff and commit both.
//!
//!   `cargo test --test regen_oracles --features regen`

use ruma_lean::{resolve_lean, LeanEvent, StateResVersion};
use serde_json::Value;
use std::collections::{BTreeMap, HashMap};

fn load_fixture(path: &str) -> Vec<LeanEvent> {
    let content = std::fs::read_to_string(path).unwrap_or_else(|_| panic!("Missing {path}"));
    let val: Value = serde_json::from_str(&content).unwrap();
    if val.is_array() {
        serde_json::from_value(val).unwrap()
    } else {
        serde_json::from_value(val["events"].clone()).unwrap()
    }
}

fn to_event_map(events: &[LeanEvent]) -> HashMap<String, LeanEvent> {
    events
        .iter()
        .map(|e| (e.event_id.clone(), e.clone()))
        .collect()
}

fn write_oracle(fixture_path: &str, oracle_path: &str, version: StateResVersion) {
    let existing: Value = std::fs::read_to_string(oracle_path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or(serde_json::json!({}));
    let room_id = existing["room_id"].as_str().unwrap_or("").to_string();
    let description = format!(
        "Generated by ruma-lean resolve_lean (version={version:?}). \
         Re-run: cargo test --test regen_oracles --features regen"
    );

    eprintln!("Resolving {fixture_path}...");
    let events = load_fixture(fixture_path);
    let map = to_event_map(&events);
    let resolved = resolve_lean(BTreeMap::new(), map.clone(), &map, version);

    let mut entries: Vec<Value> = resolved
        .into_iter()
        .map(|((t, sk), eid)| {
            serde_json::json!({
                "type": t,
                "state_key": sk.unwrap_or_default(),
                "event_id": eid,
            })
        })
        .collect();
    entries.sort_by(|a, b| {
        let ta = a["type"].as_str().unwrap_or("");
        let tb = b["type"].as_str().unwrap_or("");
        let ska = a["state_key"].as_str().unwrap_or("");
        let skb = b["state_key"].as_str().unwrap_or("");
        ta.cmp(tb).then(ska.cmp(skb))
    });

    let oracle = serde_json::json!({
        "room_id": room_id,
        "source": "ruma-lean resolve_lean",
        "description": description,
        "resolved_state": entries,
    });
    let out = serde_json::to_string_pretty(&oracle).unwrap();
    std::fs::write(oracle_path, out + "\n").unwrap();
    eprintln!("Wrote {oracle_path}");
}

fn main() {
    write_oracle(
        "res/real_dag_52k_room.json",
        "res/expected/oracle_52k_room.json",
        StateResVersion::V2,
    );
    write_oracle(
        "res/real_dag_nheko.json",
        "res/expected/oracle_nheko_room.json",
        StateResVersion::V2,
    );
    write_oracle(
        "res/real_matrix_state_v2_1.json",
        "res/expected/oracle_v2_1_room.json",
        StateResVersion::V2_1,
    );
    eprintln!("Done. Review `git diff res/expected/` before committing.");
}
